services:
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data: